---
http_interactions:
- request:
    method: get
    uri: https://api.vk.com/method/users.get?access_token=incorrect_token&fields=first_name,last_name
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
      Host:
      - api.vk.com
  response:
    status:
      code: 200
      message: OK
    headers:
      Server:
      - Apache
      Date:
      - Sat, 27 Jan 2018 19:48:31 GMT
      Content-Type:
      - application/json; charset=utf-8
      Content-Length:
      - '169'
      Connection:
      - keep-alive
      X-Powered-By:
      - PHP/3.14565
      Set-Cookie:
      - remixlang=0; expires=Tue, 05 Feb 2019 01:23:38 GMT; path=/; domain=.vk.com
      Pragma:
      - no-cache
      Cache-Control:
      - no-store
    body:
      encoding: ASCII-8BIT
      string: '{"error":{"error_code":5,"error_msg":"User authorization failed: invalid
        access_token (4).","request_params":[{"key":"oauth","value":"1"},{"key":"method","value":"users.get"},{"key":"fields","value":"first_name,last_name"}]}}'
    http_version: 
  recorded_at: Sat, 27 Jan 2018 19:48:32 GMT
recorded_with: VCR 4.0.0
