---
http_interactions:
- request:
    method: get
    uri: https://www.googleapis.com/oauth2/v3/tokeninfo?id_token=correct_token
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
      Host:
      - www.googleapis.com
  response:
    status:
      code: 400
      message: Bad Request
    headers:
      Vary:
      - Origin
      - X-Origin
      Content-Type:
      - application/json; charset=UTF-8
      Date:
      - Sat, 27 Jan 2018 19:48:31 GMT
      Expires:
      - Sat, 27 Jan 2018 19:48:31 GMT
      Cache-Control:
      - private, max-age=0
      X-Content-Type-Options:
      - nosniff
      X-Frame-Options:
      - SAMEORIGIN
      X-Xss-Protection:
      - 1; mode=block
      Server:
      - GSE
      Alt-Svc:
      - hq=":443"; ma=2592000; quic=51303431; quic=51303339; quic=51303338; quic=51303337;
        quic=51303335,quic=":443"; ma=2592000; v="41,39,38,37,35"
      Transfer-Encoding:
      - chunked
    body:
      encoding: ASCII-8BIT
      string: |
        {
         "error_description": "Invalid Value"
        }
    http_version: 
  recorded_at: Sat, 27 Jan 2018 19:48:32 GMT
recorded_with: VCR 4.0.0
